- name: Nginx servers
  hosts: all
  remote_user: ubuntu
  become: true

  tasks:

  - name: Update apt cache
    apt:
      update_cache: yes

  - name: Installing nginx
    apt:
      name: nginx
      state: latest

  - name: Ensure that nginx is started
    ansible.builtin.service:
      name: nginx
      state: started 